### ISSUE TITLE
Application Installation File

### ISSUE THREAD

**Issue by Warlord1981** [TheElixZammuto/moonlight-xbox#10]
Hello @TheElixZammuto  and many thanks for your work. One question please: For the love of me how do i install the application? I have enabled dev mode on the console but iam not a dev nor have i experience with visual studio etc. Do i need to compile the appx somehow? Because in the code I can see no appx files. Thank you in advance!

**Comment by TheElixZammuto** [comment]
Hi, appx files can be found in the release section of the Github page, at this URL: https://github.com/TheElixZammuto/moonlight-xbox/releases
