### ISSUE TITLE
Moonlight instant crash after connection to host

### ISSUE THREAD

**Issue by vinnie1234** [TheElixZammuto/moonlight-xbox#102]
**Describe the bug**
When I start the the app and connect it to the host the app crasht instant! 

**To Reproduce**
1. Open Moonlight UWP
2. Connect to Host

**Expected behavior**
Not crashing

**Screenshots or Videos**
https://youtu.be/6m-AFB-CUHM 

** Logs **
No time to see logs

**Guest Information:**
 - Xbox Model :Xbox Series X
 - TV Resolution: 4K ( But I tried to change this settings in Moonlight to every other resolution) 

**Host Information**
- Operating System: Windows
- Host Software: GeForce Experience
- Monitor Resolutions: 1440

**Comment by pugeman** [comment]
When I set to h264 , it crashed instantly, but h265 working fine

**Comment by vinnie1234** [comment]
H264 and h265 crashed both instantly for me

**Comment by geovannimp** [comment]
Same problem with Xbox Series S and sunshine, both h264 and h265.

**Comment by MajorP93** [comment]
Can confirm. h265 is working on Xbox Series X, h264 causes instant crash.

**Comment by vinnie1234** [comment]
@MajorP93 can you send all you settings? Maby I did something else wrong

**Comment by MajorP93** [comment]
> vinnie1234

I use Sunshine instead of GeForce Experience on my host system.
GeForce Experience did not work well for me. I find Sunshine to be the better stream host application.
Xbox system resolution is set to 4k.
In moonlight scaling is set to 4k in general settings.
In moonlight host specific settings I set resolution to 3840 × 2160, fps to 60, bitrate to 60000, and changed codec from h.264 to HEVC.

**Comment by MajorP93** [comment]
@TheElixZammuto any plans for looking into fixing H.264? That would be highly appreciated as H.264 is preferred for a low latency setup.
BTW: thanks for your awesome work!

**Comment by vinnie1234** [comment]
I've tried every setting, but always a direct crash

**Comment by MajorP93** [comment]
> I've tried every setting, but always a direct crash

try using sunshine instead of geforce experience

**Comment by TheElixZammuto** [comment]
Can you check if version 1.15.3 now works as expected?

**Comment by MajorP93** [comment]
> Can you check if version 1.15.3 now works as expected?

After installing the new version the top of the screen is **flickering** when I stream content from my PC to my Xbox using your app.

**Comment by vinnie1234** [comment]
Sorry for my late reaction. 

I did change to Sunshine and now I have some video. I did change the settings to:
`In moonlight host specific settings I set resolution to 3840 × 2160, fps to 60, bitrate to 60000, and changed codec from h.264 to HEVC.`

But now I have a small screen and the quality is terrible... 
https://youtu.be/5ITT_LLPxxM

**Comment by TheElixZammuto** [comment]
> Sorry for my late reaction.
> 
> I did change to Sunshine and now I have some video. I did change the settings to: `In moonlight host specific settings I set resolution to 3840 × 2160, fps to 60, bitrate to 60000, and changed codec from h.264 to HEVC.`
> 
> But now I have a small screen and the quality is terrible... https://youtu.be/5ITT_LLPxxM

Can you do the same video with the logs enabled?
Does the same happen with H264?

**Comment by vinnie1234** [comment]
H264 same problem, but also crashed 5 seconde after it starten.

Video HEVC
https://youtu.be/OO6d8_2mArg

**Comment by vinnie1234** [comment]
I don't know its relevant, but my PC specs:

https://www.userbenchmark.com/UserRun/66618658

**Comment by TheElixZammuto** [comment]
Any improvement with version 1.16.2?

**Comment by vinnie1234** [comment]
Im really busy at the time. I hope I have some time soon to test it. I will let you know!
