### ISSUE TITLE
2 Controllers add massive input lag

### ISSUE THREAD

**Issue by XexuWilder** [TheElixZammuto/moonlight-xbox#105]
If you use 2 controllers on xbox Series S, input lag increase a lot, you can disconnect one and there will be no problem.
When using 2 controllers, both are registered perfectly, but the input lag is massive.

1. Pair 2 controllers on xbox (in my case, xbox Series S)
2. execute Moonlight UWP and connect to your host
3. Input lag is high using any controller
4. disconect one controller, input lag returns to normal

**Expected behavior**
When connecting 2 controllers input lag shouldn't change

** Logs **
I don't see any logs or info helpful with this, the "Average response  xx ms" doesn't change.

**Guest Information:**
 - Xbox Model: Xbox Series S
 - TV Resolution: 4K and host sending 1080 60fps

**Host Information**
- Operating System: Windows 11 + sunshine (AMD 6700xt)
- Host Software: Sunshine
- Monitor Resolutions: 1080, 1440, 2160

**Comment by TriangleSteve** [comment]
Having the same issue, noticed it yesterday, I had a hunch it might have been from an Xbox system update.

Guest Information:

- Xbox Model: Xbox Series X
- TV Resolution: 4K and host sending 1080 60fps

Host Information

- Operating System: Windows 11 (3060Ti)
- Host Software: Sunshine
- Monitor Resolutions: 1080

**Comment by garbma** [comment]
Experiencing the same issue here.

Guest Information:

Xbox Model: Xbox Series S
TV Resolution: 1080p and host sending 1080 60fps
Host Information

Operating System: Windows 11 (3070)
Host Software: Sunshine
Monitor Resolutions: 1080

**Comment by j-scrizz** [comment]
Yep I'm getting this again too. I remember it happened in a version a while back and Elix managed to fix it up pretty quickly.

**Comment by TheElixZammuto** [comment]
I've fixed while making fixes for #107, if it works as expected I'll upload the fixed version soon

**Comment by TheElixZammuto** [comment]
Version 1.15.6 with this fix is now pending certification in the MS Store, it should be available to you in the following hours

**Comment by ssztemberg** [comment]
works great, thanks!

**Comment by XexuWilder** [comment]
Working great!! thank you very much!
