### ISSUE TITLE
Hitting the backspace on a single digit number in the Bitrate setting / attempting to clear the setting causes a crash.

### ISSUE THREAD

**Issue by JackByrne** [TheElixZammuto/moonlight-xbox#111]
**Describe the bug**
When changing the settings, if you hit the backspace on any single digit number (to attempt to clear the value) then the app crashes. 

**To Reproduce**
1. Go to a connected host
2. Click on Settings
3. Backspace a single digit number
4. App should then crash/close

**Expected behavior**
Would expect app to remain open and present an invalid Bitrate message / validation.

**Screenshots or Videos**
Can provide if needed.

** Logs **
No logs.

**Guest Information:**
 - Xbox Model: Xbox One
 - TV Resolution: 1080p

**Host Information**
- Operating System: Windows
- Host Software: Sunshine
- Monitor Resolutions: 3840 x 2160

**Comment by TheElixZammuto** [comment]
Version 1.16.2 has now a slider instead of the input, so I can close this, thank you!
