### ISSUE TITLE
Can't do anything, pairing doesn't work and app crashes after validating the pin in web ui

### ISSUE THREAD

**Issue by thndgonz** [TheElixZammuto/moonlight-xbox#114]
Client device:
xbox series x 
Host information:
Arch linux

Never had issues with my Odin handheld (android moonlight app) but this application on Xbox is just constantly crashing. I can't do anything. PIN is working because it validates in moonlight's web ui but the xbox app just hangs and crash. 

![image](https://github.com/TheElixZammuto/moonlight-xbox/assets/80124/06ccce05-40c9-44e8-8fdb-3d094e3d9bab)

**Comment by thndgonz** [comment]
Nevermind, the RTSP failed somewhere but the client didn't know how to handle it so it just crashed. RTSP stays forever hanging.

**Comment by TheElixZammuto** [comment]
Any change with version 1.16.2?

**Comment by thndgonz** [comment]
> Any change with version 1.16.2?

it has been working pretty good now.
