### ISSUE TITLE
Request: Introduce shortcut or menu entry for Xbox button

### ISSUE THREAD

**Issue by Gargitt** [TheElixZammuto/moonlight-xbox#115]
As far as I know the current way to send a click of the Xbox button to the host is:
1. Press Menu+Select to open Moonlight menu
2. Press A to select "Enable Mouse Mode"
3. Press B to send Xbox button press
4. [Xbox menu opens]
5. Press menu+select
6. Press A to select "Disable mouse mode"

In my opinion these are too many steps for simulating a single button click.
I use that button quite often as I use Steam Big Picture Mode as the main launcher and the button opens its options to configure/end a game.

Of course, the best solution would be to introduce a new shortcut for the xbox button.
However, I understand that this may be difficult due to incompability with shortcuts of certain games.
The second best solution would be to enter a new entry to the Moonlight menu like "Press Xbox/Guid button" below "Enable mouse mode" (or at first place but I guess some regular users are already used to the current ordering).

**Comment by jsmurray2** [comment]
Came here looking for this! A shortcut to press the Xbox button would be extremely useful, especially when playing games in Steam Big Picture Mode where the "home" button is necessary to open the Steam overlay. I would suggest a simply Menu+Select>Xbox Button as a quick shortcut.

**Comment by ArthurSmoke** [comment]
Need this shortcut！！

**Comment by TheElixZammuto** [comment]
Version 1.16.2 has now the Xbox guide button on the menubar, closing this
