### ISSUE TITLE
No streaming options on Series S

### ISSUE THREAD

**Issue by LuizSerapiao** [TheElixZammuto/moonlight-xbox#118]
Reading the repo, I believe the series S uses the xbox one fat defaults and hides options. App works well but streaming quality and latency are worse then any other device in my home for lack of these options. Is it possible to add a "Series" version so the S is not limited to xbone version?
Even easier, could de original xbox version get the menu back and just have a warning to not use it in the original xbox?

**Comment by TheElixZammuto** [comment]
The menu is still there, you have to open a computer menu before since the resolution, FPS, bitrate etc is specific for each PC.
