### ISSUE TITLE
Help! - Failed to Connect to [IP]

### ISSUE THREAD

**Issue by hirakkopk** [TheElixZammuto/moonlight-xbox#121]
I was using Moonlight in the morning on my xbox series s. In the afternoon, I saw that my xbox was updating Moonlight, but when I opened it, I can no longer connect to my pc.

I removed the host, restarted the pc, turned the xbox off and on, uninstalled and installed Sunshine and Moonlight and the same error always occurs when I enter the IP: Failed to connect to "IP".

After the update, I simply can't connect to my PC anymore.
I have Moonlight on my cell phone and my iPad and they are all working. So it's not a problem with my network or PC

Please, someone help me solve this problem. I basically only use moonlight on my xbox lol

**Comment by daymickcorr** [comment]
Same issue here cant connect to pc after update. I reinstalled sunshine to latest version

**Comment by yamalight** [comment]
Same here, after last update - Moonlight Xbox no longer sees host as "online". All other clients still work fine.

**Comment by TriangleSteve** [comment]
Same here as well, Xbox Series X, host running Sunshine 0.22.2

If anyone's able to get it to work on an older version of Sunshine maybe downgrading could be a temporary fix

**Comment by NicolasBtnr** [comment]
Same issue, it worked perfectly before last update

**Comment by TheElixZammuto** [comment]
I think I definetly broke something after the update. I'll Cook an hotfix early tomorrow , Sorry for the inconvenience!

**Comment by TheElixZammuto** [comment]
I've uploaded version 1.16.1 with the fix on both GitHub and MS Store (as always, it might need a couple of hours before going live), thank you for your patience!

**Comment by TheElixZammuto** [comment]
Verified over on Discord that it's working as expected, closing this
