### ISSUE TITLE
UI/settings issues

### ISSUE THREAD

**Issue by ReenigneArcher** [TheElixZammuto/moonlight-xbox#13]
Thank you making this awesome app! These issues are for the store published version of the app (version 1.8.3.70 according to my console). Probably irrelevant, but I am using an Xbox One X modded with internal SSD.

- [ ] When adding a new host, the start (menu) button does not exit the on screen keyboard (same for changing bitrate keyboard)... also selecting the "button" on the keyboard does not exit it. You must press "B" to exit the keyboard. (still present in 1.10.0.70)
- [x] The B button exits the app in some cases when it shouldn't, example
    - Open the app from cold start
    - Go to settings cog menu
    - Press B
- [x] Autostart host does not start the host when the app is launched (edit: one day later it worked, but not consistently)
- [x] Autostart app will restart the app after force closing the app (sometimes)
- [ ] When streaming, menu + back button combo should have an option to "close app", instead of just "disconnect"

**Comment by Stromduster** [comment]
Did you try last published version (1.8.10.70 on retail)? I didn't experienced your issues 1, 2 and 5 with it, on a unmodified Series X. Didn't tried Autostart though.

**Comment by ReenigneArcher** [comment]
> Did you try the last published version (1.8.10.70 on retail)? I didn't experienced your issues 1, 2 and 5 with it, on a unmodified Series X. Didn't tried Autostart though.

I have not re-evaluated these in detail yet. If I recall 2 and 3 were improved.

For number 5, I can't disconnect from the stream on the latest versions. See #17

**Comment by ReenigneArcher** [comment]
Been a while since I've messed with this app, but seems to be greatly improved! I've updated my original comment.

**Comment by TheElixZammuto** [comment]
Version 1.13 should improve almost everything here
