### ISSUE TITLE
Got status 503 from Moonlight init

### ISSUE THREAD

**Issue by xmceflp** [TheElixZammuto/moonlight-xbox#15]
Hi, thanks for this amazing project.

"Got status 503 from Moonlight init" error happens when starting connection to host (Using OpenStream)

*I already tried without Remote Play and the same error happens
![Captura de tela 2022-01-15 190007](https://user-images.githubusercontent.com/46977733/149639019-874bf136-02f0-4ef5-a706-0bebaf5ebeea.png)

**Comment by TheElixZammuto** [comment]
Hi, 
does restarting both openstreamhost.exe and openstreamapp.exe resolve the issue? 

Also OpenStream is not maintened anymore, you should use Sunshine or Maxximizer (which is a packaged version of Sunshine - https://github.com/Sean-MaximumSettings/Maxximizer-Sunshine)

**Comment by FridgeRacer** [comment]
I'm running into to this issue with an Arch Linux host with Sunshine, it works when streaming to Moonlight on my Arch Linux laptop and Android phone, but I get this error on Xbox Series X, downloaded from the Store (can't enable devmode to install the latest version I'm afraid).

The host uses an RX 6700 XT and VA-API for encoding.

I did manage to make it work before (about two months or a month ago?), but after a GPU swap and reinstall of Arch Linux on the host between then and now, I get this error. The previous GPU was a GeForce GTX 1060 6GB and I used NVENC for encoding then.

I'm not sure what info from my setup could help, or what this error code even means, so please let me know if there's anything I can supply to help.

I've tried restarting Sunshine, my host and the Xbox (cold reboot), checked the config and reset it to defaults.

**Comment by TheElixZammuto** [comment]
In general, a 503 error in Sunshine indicates that the Streaming Sessions used by sunshine are all used. In general force-closing the app in the Web UI (Troubleshooting -> Force Close) can help with this

**Comment by sixpixel** [comment]
I’m running into this same issue trying to stream using Sunshine on Windows 11 with an. RTX 3080. I am able to stream 1080p (though it’s having a frame jump every second or so), but any time I try to launch a 4K stream, it immediately gives me the 503 init error. I’ve tried the force close too as well as restarting Sunshine and the computer as a whole and it still throws the error. any ideas?

**Comment by TheElixZammuto** [comment]
Version 1.13 now should give a better error message on why it happens. Also it fixes a problem with Sunshine and 4K resolution that would cause this 503 error. Would you mind trying this again?

**Comment by cgarst** [comment]
Having this error as well with seemingly no way to get it running again. My first connection at default settings worked, but then when I boosted the resolution and bitrate it went to this. Setting it back to defaults and attempting reboots doesn't fix.

I have the latest store version currently but the error message is not more descriptive.

**Comment by TheElixZammuto** [comment]
Latest version is 1.13, that has a fix specific to this issue. I would suggest to try this again in a couple of hours,

**Comment by S3LL1G28** [comment]
Hi, 
I'm using moonlight 1.13 on an updated rpi 4 with the last version of sunshine 0.19.1.d70d084f9fbb4e0150977a89d94937418a3ccf9c.

and frequently got an error 503.

How can I give more information to ffind what happened ?

**Comment by TheElixZammuto** [comment]
@S3LL1G28 send the Moonlight logs please

**Comment by TheElixZammuto** [comment]
Version 1.13.7 is now live on the store. Do you have different error messages?

**Comment by sixpixel** [comment]
Unfortunately if this did fix the issue, I’m now experiencing a crash any time I try to launch a 4K stream. Anytime I click to start a game with resolution set to 3840x2160, the screen just goes black and kicks me back out to the Xbox Home Screen. I can connect using a 1080p stream okay, but 4K won’t work at all anymore

**Comment by TheElixZammuto** [comment]
> Unfortunately if this did fix the issue, I’m now experiencing a crash any time I try to launch a 4K stream. Anytime I click to start a game with resolution set to 3840x2160, the screen just goes black and kicks me back out to the Xbox Home Screen. I can connect using a 1080p stream okay, but 4K won’t work at all anymore

Gotcha, if you have enabled the sharing of crash reports with developers on your Xbox I should be able to check out, this is probably the same issue as #74, unrelated to this one
