### ISSUE TITLE
Hello, thank you for making this tool!

### ISSUE THREAD

**Issue by wwc1132038086** [TheElixZammuto/moonlight-xbox#16]
I'm sorry because I don't have Xbox developer qualification. I currently use the retail version of moonlight. I see that the current version has been updated to version 1.88 and seems to solve the Caton problem in the case of 60fps. I'm looking forward to using him, so can you update the retail store version of moonlight? Thank you for developing this application. You are my hero!

**Comment by TheElixZammuto** [comment]
Yup, I'm more conservative in uploading store builds. But since there should be no regressions now I can publish it on the store
