### ISSUE TITLE
Disconnect causes Moonlight to freeze

### ISSUE THREAD

**Issue by ReenigneArcher** [TheElixZammuto/moonlight-xbox#17]
With Xbox One X and retail versions 1.8.8.70 and 1.8.9.70, Disconnect does not work correctly.

Using GeForce Experience (not sure about other hosts like Sunshine at the moment).

Reproduce steps:
1. Open Moonlight
2. Open app (in my case Desktop) on a host (make sure app was not already running)
3. After connection try to Disconnect
4. App freezes

Additional information:
If I manually close `nvstreamer.exe`, Disconnect will work.

Additionally, if I try to Disconnect, and Moonlight app freezes... Then force quit Moonlight. Re-open Moonlight the session is still active. Open the session and Disconnect. Then the Disconnect will work (edit: sometimes)... So appears that Disconnect fails if the session was established during that launch, but if the session was already active then the Disconnect succeeds.

Last known working version: 1.8.3.70 retail (if I recall)

**Comment by Stromduster** [comment]
Same on Xbox Series X with 1.8.9.70.

**Comment by wwc1132038086** [comment]
The latest retail version has a slight lag issue after switching to 60fps, but it returns to normal after a while, and then there is a stutter lag.
At 30fps there is no such problem, the lag is stable.

**Comment by TheElixZammuto** [comment]
#26 (that should fix this issue) was merged in this build: https://github.com/TheElixZammuto/moonlight-xbox/suites/5533890570/artifacts/177901227

Can you check this out?

**Comment by ReenigneArcher** [comment]
> #26 (that should fix this issue) was merged in this build: https://github.com/TheElixZammuto/moonlight-xbox/suites/5533890570/artifacts/177901227
> 
> Can you check this out?

Cool! I don't have dev mode activated currently. I'll look into setting up dev mode so I can help you test.

**Comment by Stromduster** [comment]
I just tried it on Dev mode, v1.8.10.0 on xbox series x. Didn't experienced the issue :)

**Comment by ReenigneArcher** [comment]
> I just tried it on Dev mode, v1.8.10.0 on xbox series x. Didn't experienced the issue :)

I still have this issue in 1.8.12.70.

**Comment by ReenigneArcher** [comment]
> I don't have it on retail 1.8.14.70 either. Did you tried it? I suppose it could be one x related if you still experience it...

I will try later, I didn't realize there were new releases.

**Comment by ReenigneArcher** [comment]
I no longer have this issue as far as I can tell.
