### ISSUE TITLE
[FEATURE REQUEST] option or hotkey to change mouse speed

### ISSUE THREAD

**Issue by ip0p** [TheElixZammuto/moonlight-xbox#21]
Mouse speed is sometimes really slow. Would be nice to have an option for that. :)

**Comment by SilviuGamer1** [comment]
What combination would be suitable? I might be able to add this feature.

**Comment by TheElixZammuto** [comment]
> What combination would be suitable? I might be able to add this feature.

I would avoid to add new controller combinations, especially since I think this is an action that would happen rarely during the stream. Maybe we should add a Slider in the app flyover? (The one that is opened by pressing Menu + View)

**Comment by SilviuGamer1** [comment]
Good idea I will try to add that. Like a slider that would increase both the X and the Y value at the same time.

**Comment by TheElixZammuto** [comment]
Version 1.12.0 has now a setting in the app settings to change mouse Speed
