### ISSUE TITLE
image jitterring

### ISSUE THREAD

**Issue by yangtfu** [TheElixZammuto/moonlight-xbox#22]
I'm using sunshine on a deskmini x300 with amd 4650g gpu and moonlight on xbox one s.

**Comment by TheElixZammuto** [comment]
Hi, do you have Dev Mode? I have a build that can maybe fix the issue but I would like some feedback before publishing it to the store

**Comment by expostarv2** [comment]
> Hi, do you have Dev Mode? I have a build that can maybe fix the issue but I would like some feedback before publishing it to the store
> 
> https://github.com/TheElixZammuto/moonlight-xbox/suites/5598764010/artifacts/181751916

I'm also experiencing screen tearing with sunshine/Xbox one x. Though I do not have dev mode, I will regularly test new versions pushed to the store

**Comment by TheElixZammuto** [comment]
Updated the retail version to 1.10.14 which you can check for testing

**Comment by expostarv2** [comment]
Tested 1.8.14.70 with xbox one x/sunshine. Issue still present. Tested both 720p and 1080p as well as 30fps and 60fps. Gameplay latency is great framers stays steady. However going from a pause menu to gameplay caused rendering time to double and freeze images for a few seconds before stabilizing. I'm not sure if this is relevant but standard video playback was significantly worse, only able to reach 20fps and heavy screen tearing

**Comment by CWftw** [comment]
Any update on this? I was hoping to move from Moonlight on Android TV (Fire Stick) to this to reduce controller latency and get rumble which is sadly missing there. I was happy to find rumble is indeed working but am not able to play anything due to low FPS and massive "jittering" of the video

**Comment by Nun-z** [comment]
@CWftw Are you on a Series console?  If so, the upcoming fix #31 massively improves this with the new codec.

**Comment by TheElixZammuto** [comment]
I have refactored the renderer, using a frame pull approach instead of a push one. This eliminates all the multithread code and simplifies the implementation.

It's still a bit glitchy, so a couple tries would be needed to make the connection work, but I would like to have some early feedback on this, thank you!

https://github.com/TheElixZammuto/moonlight-xbox/suites/6582126521/artifacts/246693976

**Comment by CWftw** [comment]
> @CWftw Are you on a Series console? If so, the upcoming fix #31 massively improves this with the new codec.

No, just a One.



> I have refactored the renderer, using a frame pull approach instead of a push one. This eliminates all the multithread code and simplifies the implementation.
> 
> It's still a bit glitchy, so a couple tries would be needed to make the connection work, but I would like to have some early feedback on this, thank you!
> 
> https://github.com/TheElixZammuto/moonlight-xbox/suites/6582126521/artifacts/246693976

This sounds really promising! I would love to test it out but apparently my "App Developer enrollment has been disabled", thanks Microsoft. I will try to get my developer account reactivated, but of course I will also test any retail releases as they come.

**Comment by TheElixZammuto** [comment]
Any changes with version 1.9.0? (It's already on the MS Store)
