### ISSUE TITLE
Sound is played on both PC and Xbox Series X

### ISSUE THREAD

**Issue by Stromduster** [TheElixZammuto/moonlight-xbox#23]
It's been a few version I've the problem, the sound is played on both the streamed PC with GeForce Experience (windows 10 and then 11) and the Moonlight client (1.8.10.70 retail).

I'm not sure from which version it appeared, but it's at least since 1.8.0.

If needed, I can check various previous release on Dev mode later.

**Comment by Stromduster** [comment]
FYI, just the same on retail 1.8.14.70.

**Comment by TheElixZammuto** [comment]
Any changes with version 1.9.0? (It's already on the MS Store)

**Comment by Stromduster** [comment]
I tried with 1.9.70, and now, the app just crash after 2 seconds when launching the streaming... (systematically). I didn't hear the audio from my pc though.

**Comment by Stromduster** [comment]
Then, I'll try on retail, to collect some logs.

**Comment by TheElixZammuto** [comment]
Thank you, Crash dumps generated by the Xbox are Very useful in these cases

**Comment by Stromduster** [comment]
> Thank you, Crash dumps generated by the Xbox are Very useful in these cases

Indeed, I only got the issue with 1080p. I'll send you the dump in a few minutes.

**Comment by TheElixZammuto** [comment]
Any change with this build? https://github.com/TheElixZammuto/moonlight-xbox/suites/6659860254/artifacts/251890943

**Comment by Stromduster** [comment]
> Any change with this build? https://github.com/TheElixZammuto/moonlight-xbox/suites/6659860254/artifacts/251890943

No issue with this one. I can stream in 1080p, and the sound is only played on the xbox :).

**Comment by TheElixZammuto** [comment]
Wonderful and Thank you, closing this!
