### ISSUE TITLE
Host status not updated on Series X

### ISSUE THREAD

**Issue by Stromduster** [TheElixZammuto/moonlight-xbox#24]
At least since version 1.8.9 (retail and dev mode), the host status is not updated on Series X. The Moonlight app has to be exited via Home+start button from the home screen, and relaunched, to update the host status/connectivity.

I had the issue with a desktop and laptop pc, on windows 11, as host.

**Comment by Stromduster** [comment]
The issue is not present anymore on 1.8.10.0 in dev mode!

**Comment by TheElixZammuto** [comment]
Wonderful, closing he issue
