### ISSUE TITLE
Image freezes, audio continues

### ISSUE THREAD

**Issue by blitz2kx** [TheElixZammuto/moonlight-xbox#25]
Hi, thanks for your work on this project! Currently when playing any stream after sometime the image will freeze, yet audio will continue. Control inputs also continuing to work, but image will not be restored unless user goes back to home and reloads app.

Tested on:
Xbox One X
Xbox Series X
Xbox Series S.

Also tried multiple resolution, framerate, and bitrate settings. Increasing bitrate let's stream work for a few minutes longer but ultimately will break eventually (1minute to 5minutes).

All hosts and clients are hardwired with LAN.

**Comment by joaopedrosgs** [comment]
Same problem here

**Comment by MichaelMKenny** [comment]
Same problem here as well.
For me, the video sometimes keeps playing back the last second or two repeatedly, until I go home, then back to the app. Then I can play again for a bit.

Appreciate the dev’s hard work.

**Comment by TheElixZammuto** [comment]
If you have Dev Mode, can you test this? https://github.com/TheElixZammuto/moonlight-xbox/suites/5598764010/artifacts/181751916

**Comment by TheElixZammuto** [comment]
Pushed on the Store version 1.10.14 which should include the fix above. If there's no other feedback, I'll close this issue in the following days

**Comment by joaopedrosgs** [comment]
> UPDATE: After almost an hour of playing around - I can confirm I did not have a single image drop with this build. Video/Audio even controller vibration all worked out great testing on the Series X via LAN with host PC.
> 
> I would note that when the stream is first initialized input lag is very bad - feels like over 1s, however interestingly once the stream is going for a couple of minutes its almost like it catches up and then its a

Waiting for it to become available here so I can test.

**Comment by adrianolls** [comment]
1.8.14.70 i'm still facing the freezing, waiting for the update on store to be able to make new tests.
