### ISSUE TITLE
Suggestion - Include mention of Releases tab for newbies

### ISSUE THREAD

**Issue by KJPalmer24** [TheElixZammuto/moonlight-xbox#29]
Thanks for creating this app for the Xbox!

As someone who has basic coding knowledge, I thought I could handle the readme/build instructions in the Repo to get this to work, but I admit I was stymied by many issues. I've been asking friends for help, trying to find solutions online, etc.
I was pretty frustrated to find that in the closed Issues tab, I found someone with a similar issue, and in there, that was the only mention of the "Releases" tab, which had exactly what I wanted, just the packaged files required to plug into the Xbox. As someone with no desire to build the project myself, I was pleased to finally find this option! It's such a hidden little button on the Repo that I didn't even realise I could click on it, and it didn't occur to me that it could have exactly what I needed behind it either.

I would have been up and running with the XSX and this app about 3 or 4 days earlier if there was any indication in the introductory documentation that you can find the latest pre-packaged builds in the Releases tab. For those of us who aren't coders or app developers or familiar with GitHub, it would probably help out a lot to just have that easier option pointed out to us.

That being said, I've also needed to rely on other tutorials relating to installing applications on the Xbox to know what to do with the assets in the releases tab as well. "Install the application, including dependencies" is a very vague instruction for someone who doesn't recognise the file types they are presented with, and for how simple this ended up being, I would have appreciated some more uesr-friendly steps to enable to me get this program up and running.

Thanks again for putting this together at all, I'm aware that this is a voluntary effort, so I very much appreciate the time and effort put into making this option a reality.

**Comment by TheElixZammuto** [comment]
Hi,
I'm sorry you had trouble with setting up the app.

I've changed the README to include the release and actions link, and I specified which files need to be uploaded onto Dev Mode to install the Application, Cheers!

**Comment by KJPalmer24** [comment]
Hey Elia,

This is great news! Thanks so much for including this in the
Readme. Hopefully this helps the app become more approachable for some
people.
Hope you're having a great week!

Kerry
