### ISSUE TITLE
Add 4k resolution support

### ISSUE THREAD

**Issue by gald89** [TheElixZammuto/moonlight-xbox#30]
Supporting 4k would make Moonlight work great with modern TV's. Any chance this can be done?

**Comment by dtklein7** [comment]
I'm curious if current maintainers could outline what's required to get this working.

**Comment by TheElixZammuto** [comment]
> I'm curious if current maintainers could outline what's required to get this working.

Like you already saw, there's a PR available. I don't have a 4K Monitor, TV nor an Xbox capable of 4K output (I have a VCR Xbox One), so I cannot test this. So before I can merge the existing one I need some more feedback on the PR by dev mode users.

**Comment by Nun-z** [comment]
Still no luck on this for me with an HDMI dummy plug, an XSX, and a 4k TV.  720p and 1080p work flawlessly.

**Comment by seskid** [comment]
> Still no luck on this for me with an HDMI dummy plug, an XSX, and a 4k TV. 720p and 1080p work flawlessly.

What resolution is your pc monitor?

**Comment by Nun-z** [comment]
I'm using an HDMI dummy plug rather than a monitor.  4k works with Android Moonlight with the exact same setup and conditions.

**Comment by seskid** [comment]
> I'm using an HDMI dummy plug rather than a monitor. 4k works with Android Moonlight with the exact same setup and conditions.

I wonder if this is a RTSP OPTIONS error or something else.

**Comment by Nun-z** [comment]
Let me see if I can get what the exception is.

**Comment by seskid** [comment]
> Let me see if I can get what the exception is.

Yes after testing on my 1440p monitor the 4k setting no longer works after the merge and crashes for me now too.

**Comment by seskid** [comment]
Ok I believe I have resolved this issue with a simple fix. PR is out

**Comment by TheElixZammuto** [comment]
Here's the build with the fixes made by seskid in their last PR: https://github.com/TheElixZammuto/moonlight-xbox/suites/6965355074/artifacts/272010534

**Comment by Nun-z** [comment]
It works for me now with H.265.

**Comment by seskid** [comment]
> It works for me now with H.265.

Ok great! We should be good to go.

**Comment by Nun-z** [comment]
It isn't working for me with the other codec.

**Comment by seskid** [comment]
> It isn't working for me with the other codec.

Yes it must be H.265 codec for 4k

**Comment by Nun-z** [comment]
Would it be possible to prevent it from crashing with 4K and H.264 selected when attempting to launch streaming, maybe by displaying an error message instead?  I don't know if @TheElixZammuto would prefer an error message or if the crash is okay.

**Comment by seskid** [comment]
> Would it be possible to prevent it from crashing with 4K and H.264 selected when attempting to launch streaming, maybe by displaying an error message instead? I don't know if @TheElixZammuto would prefer an error message or if the crash is okay.

Yes I'd think we could auto enforce the H.265 codec if 4k is the selected resolution and users could use H.264 otherwise.

**Comment by TheElixZammuto** [comment]
Can someone with dev mode test this? https://github.com/TheElixZammuto/moonlight-xbox/suites/7488115071/artifacts/307365824

On the app settings there's now a "Composition Scale" setting, that can be used to change how the display is scaled (Normal for 1080p or 4K for Xbox One S/X/Series S/Series X). Also there's 4K support for the host side. Also H265 is enforced on 4K resolution

**Comment by joaopedrosgs** [comment]
> Can someone with dev mode test this? https://github.com/TheElixZammuto/moonlight-xbox/suites/7488115071/artifacts/307365824
> 
> On the app settings there's now a "Composition Scale" setting, that can be used to change how the display is scaled (Normal for 1080p or 4K for Xbox One S/X/Series S/Series X). Also there's 4K support for the host side. Also H265 is enforced on 4K resolution

I've tested and these are the results:
- Setup: Xbox Series S, 4K TV, 1080 monitor, PC wired to the router and Xbox connected through 5G.
- Regardless of the settings, this happens:

https://user-images.githubusercontent.com/16986475/180604447-76cba158-c2df-46fe-bbf2-97453ebbb422.mp4

![photo_2022-07-23_09-11-21](https://user-images.githubusercontent.com/16986475/180604460-4fb5b05b-abd5-4d51-ae73-a06c95ade8e6.jpg)

Seems to be too slow to keep up with the stream, resulting in periodic frame skipping.

I tried: bitrates of 35mb and 15mb, and with hvec enabled and disable. Same results.

Also, when I tried 4k, it crashed (my monitor doesn't support it)

**Comment by seskid** [comment]
To clarify make sure to leave composition scale on normal   when using xbox one x and xbox series X no matter the resolution.

**Comment by joaopedrosgs** [comment]
> To clarify make sure to leave composition scale on normal when using xbox one x and xbox series X no matter the resolution.

the scaling works perfectly, it's just the stuttering that shouldn't be happening

**Comment by seskid** [comment]
> > To clarify make sure to leave composition scale on normal when using xbox one x and xbox series X no matter the resolution.
> 
> the scaling works perfectly, it's just the stuttering that shouldn't be happening

Mine has been fine with xbox wired. Any wifi has always been a struggle for me.

**Comment by gald89** [comment]
Any update on this?

**Comment by Nun-z** [comment]
> Can someone with dev mode test this? https://github.com/TheElixZammuto/moonlight-xbox/suites/7488115071/artifacts/307365824
> 
> On the app settings there's now a "Composition Scale" setting, that can be used to change how the display is scaled (Normal for 1080p or 4K for Xbox One S/X/Series S/Series X). Also there's 4K support for the host side. Also H265 is enforced on 4K resolution

Can you test this gald89?  I think 4K works now.  The stuttering could be from a slow connection.

**Comment by seskid** [comment]
> > Can someone with dev mode test this? https://github.com/TheElixZammuto/moonlight-xbox/suites/7488115071/artifacts/307365824
> > On the app settings there's now a "Composition Scale" setting, that can be used to change how the display is scaled (Normal for 1080p or 4K for Xbox One S/X/Series S/Series X). Also there's 4K support for the host side. Also H265 is enforced on 4K resolution
> 
> Can you test this @gald89? I think 4K works now. The stuttering could be from a slow connection.

Yes I think we push this through at this point @TheElixZammuto . Doesn't seem like we will ever have enough testers.

**Comment by Jows23** [comment]
> Can someone with dev mode test this? https://github.com/TheElixZammuto/moonlight-xbox/suites/7488115071/artifacts/307365824
> 
> On the app settings there's now a "Composition Scale" setting, that can be used to change how the display is scaled (Normal for 1080p or 4K for Xbox One S/X/Series S/Series X). Also there's 4K support for the host side. Also H265 is enforced on 4K resolution

I tested it here and it worked perfectly on Series X in 4K with H.264 Codec connected by cable and 80k bitrate. I played it for 1 hour and it worked flawlessly, my PC screen also played in 4K to my TV. I would be very grateful if you could send this update to the UWP version.

**Comment by seskid** [comment]
> > Can someone with dev mode test this? https://github.com/TheElixZammuto/moonlight-xbox/suites/7488115071/artifacts/307365824
> > On the app settings there's now a "Composition Scale" setting, that can be used to change how the display is scaled (Normal for 1080p or 4K for Xbox One S/X/Series S/Series X). Also there's 4K support for the host side. Also H265 is enforced on 4K resolution
> 
> I tested it here and it worked perfectly on Series X in 4K with H.264 Codec connected by cable and 80k bitrate. I played it for 1 hour and it worked flawlessly, my PC screen also played in 4K to my TV. I would be very grateful if you could send this update to the UWP version.

Thats great! I'll add that in the code I do automatically switch to h.265 if 4k is selected.

**Comment by Jows23** [comment]
some screens:
![IMG_5138](https://user-images.githubusercontent.com/114774215/193350940-bfd95dc6-4e14-4ef1-9adb-244ebb094fdd.jpg)
![IMG_5140](https://user-images.githubusercontent.com/114774215/193350948-ca7a28f9-2080-4217-97e6-f54946f5c396.jpg)
![IMG_5141](https://user-images.githubusercontent.com/114774215/193350962-5d98de45-e5f1-473d-80b2-72ed15bfb99c.jpg)
![IMG_5142](https://user-images.githubusercontent.com/114774215/193350972-d3ea2d32-ece0-4d81-afc4-a2ec0c04721c.jpg)
![IMG_5143](https://user-images.githubusercontent.com/114774215/193350977-d6cbff5d-87c2-405b-a975-b15a10773406.jpg)
![IMG_5144](https://user-images.githubusercontent.com/114774215/193350986-ca6dfdf6-da38-4f9d-b2fd-2e6a3c1384f8.jpg)

**Comment by Jows23** [comment]
Well, as it hasn't been updated to 4K yet, I successfully got a way to run games in 4K in the UWP version.

1 - Change your PC's resolution to 4k if it's not, on xbox leave the resolution at 1080P.
2 - Open Moonlight UWP on your xbox and load the game, choose 4k resolution in game settings (or a resolution compatible with your GPU)
3 - Without leaving Moonlight press the XBOX button on your controller and go to your xbox video settings and set the resolution to 4K.
4 - Go back to moonlight and enjoy your game running in 4K.

**Comment by TheElixZammuto** [comment]
Release 1.10 is now online with the changes made by @/seskid, let me know if everything works as expected!
