### ISSUE TITLE
Dual screen bug

### ISSUE THREAD

**Issue by troufiniou** [TheElixZammuto/moonlight-xbox#34]
Hi,

Got a little bug (or something wrong for me idk).

I have a setup with two dual screen. When I launch a game (in this case Portal 2) from moonlight, the game go to the first screen but moonlight stream the second screen.

There is a way to add an option on moonlight to stream the other screen ?

Thanks ❤️

**Comment by TheElixZammuto** [comment]
Hi,

This is not a bug per se since Moonlight hosts only supports a single monitor.

Which host software are you using? (GeForce Experience/Sunshine/OpenStream/Maxximizer?)

**Comment by troufiniou** [comment]
Hi thanks for the answer.

I use GeForce Experience.

**Comment by TheElixZammuto** [comment]
According to the Moonlight Discord Server:

> You can create a new text file and name it clone.bat, and type C:\Windows\System32\DisplaySwitch.exe /clone,
> and one called extend.bat C:\Windows\System32\DisplaySwitch.exe /extend to revert it.
> Add an exit to the end of the files to automatically close the terminal once done.
> You can then launch them using Remote Desktop or add them fas custom games in GeForce Expereince.
> Note: To make sure the file extension is .bat you should have "Show known file extensions" enabled.
> https://www.howtohaven.com/system/show-file-extensions-in-windows-explorer.shtml
> Other command line parameters for DisplaySwitch: /internal, and /external.

For more information you should use the [Moonlight Discord Server](https://discord.gg/CGg5JxN) since the problem is caused by GeForce Experience and not Moonlight-xbox (and unfortunately I don't use GFE, so I cannot personally help you)
