### ISSUE TITLE
Feature Request; play sound on pc

### ISSUE THREAD

**Issue by TheGoofBall64** [TheElixZammuto/moonlight-xbox#37]
Not a bug, but I was told to put this here by Elix on discord.

So me and my buddy (me on PC, him on xbox) use moonlight to play games in split-screen, stuff like ps3 and ps2 games in an emulator bla bla bla. the issue is, there is currently no option to allow the audio to continue playing on both the PC and xbox at the same time, so I'm left in silence while my buddy can hear everything. Would it be much a bother to add this feature soon to the xbox release please, it would be awesome if it was added soon. 

,thank you

TheGoofBall64

**Comment by TheElixZammuto** [comment]
Version 1.13 now adds this feature!
