### ISSUE TITLE
Feature request: auto start specific PC/game

### ISSUE THREAD

**Issue by ReenigneArcher** [TheElixZammuto/moonlight-xbox#4]
I appreciate your work on this project so far! This is amazing!

I know this is very early but would like to request a feature.

Please add a setting to select a PC and game to automatically start when starting the app. The reason for this request is on the Xbox I don't think it's possible to pass in any arguments (using xbox web api) like we can with Android ADB or command line options on other platforms.

**Comment by TheElixZammuto** [comment]
Version 1.8.0 should now add the feature to autostart a saved host and/or an app inside the host

**Comment by ReenigneArcher** [comment]
> Version 1.8.0 should now add the feature to autostart a saved host and/or an app inside the host

Awesome! Can't wait for this to be in the store so I can use this with RetroArcher and Plex. Thank you!
