### ISSUE TITLE
Random input lag

### ISSUE THREAD

**Issue by eduardoibarra960** [TheElixZammuto/moonlight-xbox#41]
Sometimes input lag just increases considerably without a reason, and then randomly dissapears, it renders a fast paced game unplayable

All is connected throught 1 Gbps cables and this issue isn't happening in the lower spec device I also use (FireTV Stick 4K) with the same setup

Xbox Series S seems to decode frames a lot faster than the FireTV device, so I would have the perfect streaming machine if random input lag wasn't a problem

Thank you.

**Comment by TheElixZammuto** [comment]
Probably to the new rendering system, network, decoding and rendering are done in the same thread, before that there were separate threads for handling this, which caused all sorts of issues (tearing, frame jumping and so on). One thing that can be tried is to separate the network but keep the decoding in the same thread.

**Comment by remz1337** [comment]
Same issue with Xbox One

**Comment by viktorsparda** [comment]
I tried using the app on my Xbox one x today and i had the same issue regarless of the resolution selected at 60 fps
Both computer and Xbox are connected through ethernet.
The input lag increases at random and stays high most of the time after it increases.
The stream is smooth but the input lag kills the experience

**Comment by jacobckelly** [comment]
To further muddy the waters, I tried some nonempirical testing today at 4k/150000 bitrate/hevc/60 with a 5950X+3090 to a Xbox Series X playing Crash Bandicoot.

I've found that the controller used for the Xbox has considerably more latency on input (bordering on unplayable) than the controller directly connected to my PC, with input lag bordering on imperceptible with the directly connected option. I didn't encounter any of the random input lag drops others are talking about in this thread however.

Both controllers were connected using Xbox's Wireless rather than Bluetooth.

Not sure if this helps any.

**Comment by leezerofly** [comment]
Same issue with Xbox Series X
And it seems to only happen at 60 fps
Not sure if contact with this closed issue: https://github.com/TheElixZammuto/moonlight-xbox/issues/28

**Comment by linuzel** [comment]
Hello,

I have the same issue.

It seems to be mostly input lag and not really encode/network/decode latency.

It is much better un 1080p for some reason but it is still pretty unstable, on the same host and network it is very stable and playable on the MacOS official client which would rule out a host or network issue I guess.

**Comment by eduardoibarra960** [comment]
It's just an input lag issue, I can stream with the android apk on a pretty weaker device with zero noticiable lag (even throught 5Ghz network if I'm close to the router) and 100% stability, would love to have that in this xbox uwp tho

**Comment by TheElixZammuto** [comment]
I changed some logic and improved the polling rate for inputs in version 1.12.0. Would you mind to try this and let me know if this does improve input lag? personally I tried a couple of level of Sonic Mania and I did not have any noticeable input lag

**Comment by eduardoibarra960** [comment]
Input lag is still an issue, something I have found is that on WiFi (more bandwidth, 5Ghz, full signal) the input lag seems to persist a lot more of time (couple of minutes) but eventually it goes away completely and starts to build up until it is unplayable again, while on Ethernet the issue is going back and fort between pretty lag and zero lag in a faster pace.

To me it looks like the display buffer is struggling to draw everything it has at the right framerate and starts to show previous frames that are not being cleared (drawn), but I don't have looked at the code.

**Comment by sonicsam521** [comment]
Hey thanks for the hard work! While using the latest build I enabled the stats and noticed the queue size gradually increasing from 0 to 13 then back to 0. Just an FYI, I’m playing on Ethernet at 1080p 60fps and have tried this with various bitrates. Thanks again for the builds, keep it up!

**Comment by josealruva** [comment]
> using the latest build I enabled the stats and noticed the queue size gradually

I checked and have the same issue I try in all resolutions and bitrates and or gradually increassing from 0 to 14 or randomly appear differents numbers.

**Comment by PerretDavid** [comment]
I wonder if the issue is not linked to this issue https://github.com/TheElixZammuto/moonlight-xbox/issues/72.

I only played Hogwarts Legacy (on steam), but I notice I have a significant input lag when the game seems to constantly switch between showing keyboard and gamepad shortcut. I even tried to unplug completly the mouse and keyboard on the host but it still switches constantly.

I managed somehow to have almost no input lag and during this time the game shown only gamepad shortcuts... It looks like there are conflicting inputs between mouse/keyboard emulation and gamepad controls, causing potential input lag issues.

**Comment by eduardoibarra960** [comment]
> I have added in the stats a "Qeueue Size" indicator, you can check if in case of lag the value is greater than 0? If so then we have found the culprit of our problem

Yes, the lag is directly related to the value of queue size, it slowly starts to increase 1 by 1 every couple seconds, I'm not sure if it is related to joystick input.

**Comment by TheElixZammuto** [comment]
Version 1.13.6 adds some changes to the swapchain that should improve this. Let me know if this works for you!

**Comment by eduardoibarra960** [comment]
It is fixed, I've tried some of the games that previously shown lots of input lag and they work perfect now.

**Comment by PerretDavid** [comment]
> I wonder if the issue is not linked to this issue #72.
> 
> I only tryed moonlight-xbox with Hogwarts Legacy (on steam), but I noticed I have a significant input lag when the game seems to constantly switch between showing keyboard and gamepad shortcuts. I even tried to unplug completly the mouse and keyboard on the host but it still switches constantly between the two.
> 
> I managed somehow to have almost no input lag and during this time the game shown only gamepad shortcuts... It looks like there are conflicting inputs between mouse/keyboard emulation and gamepad controls, causing potential input lag issues.

Controls switching between keyboard and gamepad and the input lag that was seen are both fixed with Hogwart Legacy on your latest release. Thanks a lot, works like a charm !
