### ISSUE TITLE
Official Windows Store App?

### ISSUE THREAD

**Issue by kohanyirobert** [TheElixZammuto/moonlight-xbox#42]
Is there a will to release this app (in the future) as an official app? The hassle with the devmode switching prevents me from trying this (as I understood when in devmode I can't run normal apps/retail games and that's too much of a hassle for the simple user). Thanks for the input!

**Comment by TheElixZammuto** [comment]
Hi,


This is the Microsoft store link that can be opened on your Xbox Browser: https://www.microsoft.com/store/apps/9MW1BS08ZBTH (as found on the README)

Happy gaming!

**Comment by kohanyirobert** [comment]
Hmm, thanks. I've searched Microsoft Store on my Xbox but didn't find this. When I read the README and I saw _Installation and Usage_ where the first step is _Enabled Dev Mode_ I got confused.

When I enter the URL in Edge I can then install the app (haven't tried, will do).

Thank you for responding, wouldn't have figured this out in ages otherwise :D

**Comment by besimple82** [comment]
Is the official Windows Store version same as dev mode version?
I test the dev mode and it display as normal full screen. However, the Windows Store version seems over scan.
Console: xbox series s with 4k60 TV
PC: win 10 with 2k monitor
Resolution setting: 1080 ( not sure if it’s 4k scaling in dev mode)
