### ISSUE TITLE
Not Available for bots to index

### ISSUE THREAD

**Issue by bruno-barros** [TheElixZammuto/moonlight-xbox#43]
I'm trying to open the app link on Xbox browser, but no luck.
I'm getting the message: Not Available for bots to index

Any help?

**Comment by TheElixZammuto** [comment]
It seems that MS Store broke itself: https://github.com/microsoft/winget-cli/discussions/2465

Adding some random parameter to the url seems to workaround the problem: https://apps.microsoft.com/store/detail/9MW1BS08ZBTH?hl=it-it&gl=IT&clid=hello

**Comment by bruno-barros** [comment]
What!? It's realy odd.
