### ISSUE TITLE
Dual monitor (maybe unrelated)

### ISSUE THREAD

**Issue by bruno-barros** [TheElixZammuto/moonlight-xbox#44]
Guys, if it's totally unrelated, close, please.

I'm use two monitors. When I open the game though Steam the Steam panel stick on the right monitor and the game on the left one.
The Moonlight app stick with the right monitor, so I can not see the game.
Is there a way to avoid this? Maybe set the Steam to use only on monitor.

**Comment by SilviuGamer1** [comment]
I dont know if im right but moonlight uses the primary display to stream meaning the one that shows "1" in windows so idk way easiest way would be to unplug the second one form the power cord and plug it back when you are at ur PC
