### ISSUE TITLE
Retail link is broken

### ISSUE THREAD

**Issue by Nun-z** [TheElixZammuto/moonlight-xbox#49]
The retail link for Moonlight (https://www.microsoft.com/store/apps/9MW1BS08ZBTH) is broken, as the app was taken down by Microsoft.

**Comment by TheElixZammuto** [comment]
Hi everyone and sorry for the silent response, but I was in contact with the Microsoft Support to check what was going on with the app. Luckily all went through with no problem and app should be up again!

**Comment by Nun-z** [comment]
The app is back up.
