### ISSUE TITLE
R2 and L2 triggers analog bug

### ISSUE THREAD

**Issue by JPP9547** [TheElixZammuto/moonlight-xbox#50]
The R2 and L2 triggers on a xbox one controller are analogs, i can just press 50% of it.
On moonlight it is bugged and when i press 50% of the r2 or l2 it becomes crazy and keeps changing from 20% to 80%

Open the stream on a xbox one s

Expected behavior
If you press the R2 or L2 triggers on 50% it registers as 20% and 80%

**Screenshots or Videos**
https://user-images.githubusercontent.com/114318448/194725505-7f914806-6db3-4a45-94d8-65f543990f63.mp4

**Guest Information:**
 - Xbox Model:  Xbox One S

 - TV Resolution: 4K, but I use on 1080p to avoid bugs

**Host Information**
- Operating System: Windows 10
- Host Software:GeForce Experience
- Monitor Resolutions: 1920-1080(1080p)

**Comment by TheElixZammuto** [comment]
Version 0.11.0 is now up on the MS Store, that should fix this bug!
