### ISSUE TITLE
Latency 60 fps 

### ISSUE THREAD

**Issue by hirakkopk** [TheElixZammuto/moonlight-xbox#53]
I'm facing unplayable latency when I'm running a game at 60 fps (Any game)

I'm playing with 50 fps (locked with nvidia panel) and it runs perfectly fine. But I'm looking for some way to run at 60 fps and I haven't had any success.

Sometimes it seems to go back to normal for a few seconds,
but after about 20 seconds the latency comes back.

I'm using 1080p, 60fps, hvec codec. I have an xbox series s and a PC with 1gb wired internet. I have an rtx 3060 GPU, but I don't think that's the problem, because it runs at 60 fps on Moonlight mobile

**Comment by Ultracoolguy** [comment]
I have a similar issue, except with me the latency feels a lot but consistent. When I cap the framerate to 30 in Moonlight settings there is a delay but it's much less noticeable. Resolution and codec don't seems to affect. My PC is using sunshine connected to the internet. I also have no issues with other versions of Moonlight.

**Comment by TheElixZammuto** [comment]
Any improvement with version 1.12.0?

**Comment by Tyrielwood** [comment]
Still much higher than 30fps at any bitrate in my experience, it's getting better and better each update, but still much higher unfortunately. 
I'm using it on the Xbox series x

**Comment by TheElixZammuto** [comment]
In the stats I've added a "Queue Size" indicator (from version 1.13.0). When the latency is too high, how does that value go? Ideally it should be 0.

**Comment by Tyrielwood** [comment]
Hey man! Thanks for all of the work on the app! 
So I tried to test with the new update, but I faced many problems unfortunately. 
To start now the 30fps is actually 60fps and vice versa, but even at 60 (the real 60), I noticed many more micro stutters. The good part is that the latency was very low, and the new queue value always at 0! 
With that said tho, I was able to test it just at 1080p because 1440p and 4k now crash the app right away, with both codecs and even at low bitrates.

**Comment by hirakkopk** [comment]
Hi! First, I would like to thank you for the update and the new features. I ran some tests and still experienced some input lag episodes, but I have the impression that it happened less frequently. When input lag occurs, the AVG render drops below 1 and the Queue goes above 0, and it keeps increasing.

Enabling Vsync increases input lag significantly, and disabling it causes small stutters. These stutters seem to reset the AVG Render, which tends to drop and cause input lag. With Vsync turned on, the stutters do not occur and the AVG Render drops until it accumulates a queue. I don't understand much about this, but this is what I noticed while doing my tests.

However, I am able to play most games without VSync. I hardly play any Xbox games anymore, after using your app I only play my Steam games because I love mods in my games. Thank you very much for your work

**Comment by TheElixZammuto** [comment]
Version 1.13.6 adds some changes to the swapchain that should improve this. Let me know if this works for you!

**Comment by hirakkopk** [comment]
Hello! I did a quick test now with vsync on/60 fps and AVG render remained stable at 16, and the queue size did not go up at all. So far it seems that the problem has been solved, I will do other tests with games that always had input lag like Red Dead 2, Stardew Valley and Days Gone and I will come back with Feedback. Thank you very much!

**Comment by hirakkopk** [comment]
I did more tests with games that always had input lag with Vsync, and I’m impressed how there is almost no input lag. It remained completely stable, I really love this App. I affirm that this problem has been solved, thank you very much!!
