### ISSUE TITLE
This doesn't seem to be available to install on Xbox anymore

### ISSUE THREAD

**Issue by moocow1452** [TheElixZammuto/moonlight-xbox#54]
Tried installing on my Xbox One, latest software. Unable to install through Microsoft Edge on the Xbox or from another computer.

**Comment by hacmx** [comment]
I have same issue

**Comment by MCardus** [comment]
In my Xbox serie X, I coudn't find it in the Xbox store directly, but I manage to install it using edge with the given link in the readme.

**Comment by sanviler** [comment]
the install link is greyed out and I can't click it

**Comment by electr0de** [comment]
Yup the same exact issue.

**Comment by TheElixZammuto** [comment]
Do you have a screenshot of the issue? The app is enabled an all markets and there's no age restrictions, so it should be able to be installed by everyone

**Comment by TechnoGangsta** [comment]
I'm having the same issue on my Xbox one, it won't take a screenshot for some reason but here is a picture. 
![IMG20230403193641](https://user-images.githubusercontent.com/76266487/229656720-06978b19-c9a1-4351-9d87-03892f7cf9f5.jpg)

**Comment by TheElixZammuto** [comment]
Hi,
I've changed the download link using the official badge by Microsoft. Let me know if it works for you

**Comment by TechnoGangsta** [comment]
> Hi,
> I've changed the download link using the official badge by Microsoft. Let me know if it works for you

This works! I did have to clear the cache and everything in edge but it did work.

**Comment by TheElixZammuto** [comment]
I've set the app as public on the Microsoft store, so it can be just searched inside the Microsoft Store on your Xbox. Let me know if it does work for you!
