### ISSUE TITLE
Support for Castor (Manual IP with port)

### ISSUE THREAD

**Issue by Dziggify** [TheElixZammuto/moonlight-xbox#55]
Heya, loving the moonlight xbox app! I hope you will continue to support it and make it better.

So, I'm using [Castor](https://retrogamecorps.com/2022/09/23/introducing-castor-split-and-stream-your-pc/) now, and it requires you to manually connect with IP but with a port number (usually 48039). I tried to connect to it from your app but it seems it's not supported? Mac and Android clients support this, so I was wondering if this is something that's possible on Xbox client.

Thanks and Happy holidays!

**Comment by TheElixZammuto** [comment]
Hi,
If you have dev mode this build should support custom ports: https://github.com/TheElixZammuto/moonlight-xbox/suites/11959901132/artifacts/627335775

**Comment by Dziggify** [comment]
Awesome stuff! Thanks for all the work man, the new store version looks way better and perform excellently.
