### ISSUE TITLE
Get Status Code 10060 ob Xbox Series X

### ISSUE THREAD

**Issue by CreLab** [TheElixZammuto/moonlight-xbox#56]
I downloaded the current version of moonlight UWP from the MS Store. Also installed the current GeForce game driver from Nvidia Website on my PC.

GeForce 1650 notebook
Nvidia Driver Version: | 528.02  WHQL
Release Date: | 2023.1.5

Than i followed all steps from the readme to start a game via moonlight on the Xbox. Game is starting on the PC correctly, Bit not streaming to Xbox. Only i get a message on the TV screen with status code 10060.

Can you help me to get the stream running?

Is the moonlight UWP version from the MS store the newest release?

Do i need a differend nvidia driver version?

**Comment by TheElixZammuto** [comment]
Hi, there were many changes during these months. Are you still interested to check this the newer version? Maybe some of these fixes did indirectly fix yours!
