### ISSUE TITLE
Doesn't work with latest GeForce Experience

### ISSUE THREAD

**Issue by eduardoibarra960** [TheElixZammuto/moonlight-xbox#58]
App just doesn't work anymore after GeForce Experience was updated to latest version

1. Start any app

It is supposed to show the normal stream, instead we get a solid sky-blue color, sound works fine tho

"Show logs" doesn't show anything on screen

 - Xbox Model: Xbox Series X
 - TV Resolution: 4K
- Operating System: Windows
- Host Software: GeForce Experience
- Monitor Resolutions: 1440p (16:9)

**Comment by Trasen** [comment]
I'm experiencing the same issue - didn't know it was because of the latest GeForceExperience update though.

**Comment by TheElixZammuto** [comment]
If you have Dev Mode, would you like to try this build? https://github.com/TheElixZammuto/moonlight-xbox/suites/10779062605/artifacts/541670889

**Comment by bg-gif** [comment]
Hey, I was having the same issues as above. I have installed the build on dev mode and it looks like its resolved the issue.
When launching the app in dev mode, it pops up an error of 400 and then continues to work

**Comment by RenezJ** [comment]
> I'm experiencing the same issue

XBox not in Dev at this moment, may try later or ill hope youll update the Store Version ;)

**Comment by riquew** [comment]
Having the same issue

**Comment by TheElixZammuto** [comment]
Version 0.11.0 is now up on the store, let me know if it works for you!

**Comment by eduardoibarra960** [comment]
It is fixed

**Comment by eduardoibarra960** [comment]
I have updated to the latest Nvidia driver 531.61 and when I start a game the stream just freezes, I can stream the desktop and it works tho.

A few weeks ago I changed from GFE to Sunshine and it worked on both Xbox's and Android's moonlight, but after the driver update it only works on the Android one.
