### ISSUE TITLE
Not displaying full screen on Series X with 4K resolution

### ISSUE THREAD

**Issue by dewhaskins** [TheElixZammuto/moonlight-xbox#6]
When using 4K display mode on Series X the video only covers the top left quadrant of the screen rather than rescaling to fill the whole screen

**Comment by TheElixZammuto** [comment]
Yup, confirmed by some users that the DirectX is giving a Window Size of 1920x1080 instead of 4K. The issue probably lies here: https://github.com/TheElixZammuto/moonlight-xbox/blob/master/Common/DeviceResources.cpp#L489

On my todo list here it is, hoping to fix it soon

**Comment by Stromduster** [comment]
I'm experiencing the same behavior, but only with the Store version on retail mode (1.8.9).I didn't experience that in dev mode. Please find a picture in attachment.

If I change resolution in settings to 1080p, Moonlight is then in full screen. 

![PXL_20220118_075658469](https://user-images.githubusercontent.com/97334817/149895751-0d84dbf1-be25-4e07-aac9-781c62858236.jpg)

**Comment by TheElixZammuto** [comment]
Quick Question: If you press both Menu + View to show the app menu, does the menu show in the lower left corner of the TV or in the lower left corner of the stream?

**Comment by Stromduster** [comment]
Lower right corner, as you can see. 
![Uploading PXL_20220122_221651605.jpg…]()

**Comment by TheElixZammuto** [comment]
Gotcha, so only the SwapChain gets set at 1080p while the UI is still set at 4k, thank you for the insight!

**Comment by Stromduster** [comment]
No problem, and thanks for your hard work!

**Comment by TheElixZammuto** [comment]
I wasn't able to test this but I "borrowed" some code from @tunip3 to change how the resolution is handled on the swapchain

Build here: https://github.com/TheElixZammuto/moonlight-xbox/suites/5033574177/artifacts/148605088

**Comment by Stromduster** [comment]
Tested in Dev mode. I didn't notice any resolution problem. However, I can't be sure it works unless I try on Retail (the issue was only when the Store version was used).

**Comment by TheElixZammuto** [comment]
> Tested in Dev mode. I didn't notice any resolution problem. However, I can't be sure it works unless I try on Retail (the issue was only when the Store version was used).

TV Settings are different between Dev and Retail. On Dev mode you can open the settings and set the TV output to 4K to check out the resolution issue

**Comment by Stromduster** [comment]
> > Tested in Dev mode. I didn't notice any resolution problem. However, I can't be sure it works unless I try on Retail (the issue was only when the Store version was used).
> 
> TV Settings are different between Dev and Retail. On Dev mode you can open the settings and set the TV output to 4K to check out the resolution issue

That's what I meant by "testing" on Dev mode. I never experienced the issue with 4k resolution set in the settings.
I only observed it on retail mode.

**Comment by TheElixZammuto** [comment]
@Stromduster published v1.8.10 with the fix above, hopefully should fix this

**Comment by dewhaskins** [comment]
> @Stromduster published v1.8.10 with the fix above, hopefully should fix this

Confirmed that has fixed the issue, thanks.

**Comment by TheElixZammuto** [comment]
Wonderful! I'm publishing the release and closing the issue then
