### ISSUE TITLE
Retail mode app update

### ISSUE THREAD

**Issue by Maceeek** [TheElixZammuto/moonlight-xbox#61]
Hi, let me start off by saying that I really appreciate that someone works on PC game streaming to Xbox (thank you!). This is seriously a greedy move from MS that there isn't any native solution. 

I've tried the retail app and it works great, but I saw that it is a pretty old version. 

Are there any plans for a new release for the retail app?

**Comment by electr0de** [comment]
Hey, can you tell me how did you get around installing the retail version? Trying the instructions on the readme, the link takes to the store page where the button "get this app" is greyed out.

**Comment by Maceeek** [comment]
I followed the instructions in readme. It is not greyed out on my side.

**Comment by TheElixZammuto** [comment]
> I've tried the retail app and it works great, but I saw that it is a pretty old version.

Hi, the retail app is always the latest stable app (which is the last release on GitHub). The commits made weren't ready to be released yet. [Version 1.12.0](https://github.com/TheElixZammuto/moonlight-xbox/releases/tag/1.12.0) should be live on the store in the following hours
