### ISSUE TITLE
Emoji not showing correctly for Sunshine app titles

### ISSUE THREAD

**Issue by erictbar** [TheElixZammuto/moonlight-xbox#63]
**Describe the bug**
I use emoji on my app list to sort my list with the emoji appearing last on the tvOS, iOS and macOS versions of Moonlight. I also use emoji to more easily find specific scripts I use to quit or open apps/utilities
Moonlight UWP does not handle this correctly on my Series S.

**To Reproduce**
1. In Sunshine settings, have apps such as 🟡Open reWASD, ❌Close Playnite and _Playnite
2. Open Moonlight on Xbox Series S (Retail or Dev mode) and select this Sunshine server

**Expected behavior**
App list should contain titles such as
🟡Open reWASD
❌Close Playnite 
and 5 other titles that begin with an emoji, and place them at the end of the list

Actual results:
Emoji are replaced with accented vowels, for example ❌ becomes â and 🟡becomes o with an x over it followed by a a backwards exclamation point, and the list is sorted by recently added to Moonlight

**Screenshots or Videos**
If applicable, add screenshots or video recordings to help explain your problem.
<img width="960" alt="2023-04-04 (1)" src="https://user-images.githubusercontent.com/332205/229811489-313d12ba-5e35-40c8-8930-6cecd96bad7d.png">

** Logs **
While pressing Menu + View and then "Show Logs", are there any relevant log lines?
Issue occurs in app UI, so I don't think I can gather logs on this

**Guest Information:**
 - Xbox Model: Xbox Series S
 - TV Resolution: 4K

**Host Information**
- Operating System: Windows 11 Pro 22H2
- Host Software: Sunshine v0.19.1
- Monitor Resolutions: 1920x1080

**Additional context**
How Moonlight displays on macOS
<img width="1552" alt="Screenshot 2023-04-04 at 9 45 28 AM" src="https://user-images.githubusercontent.com/332205/229812961-31376575-d6cf-453a-8dbc-f1f4fe247f15.png">

**Comment by TheElixZammuto** [comment]
Version 1.13 now fixes this!
