### ISSUE TITLE
Request: Sort app list alphabetically

### ISSUE THREAD

**Issue by erictbar** [TheElixZammuto/moonlight-xbox#64]
**Describe the bug**
I would like to sort my app list alphabetically, either by default or with an option.
This relates to #63 as emoji are not showing correctly, and I would like emoji to show at the end of the list, and an app with a leading underscore to display first.

**To Reproduce**
1. In Sunshine settings, have apps such as 🟡Open reWASD, ❌Close Playnite and _Playnite
2. Open Moonlight on Xbox Series S (Retail or Dev mode) and select this Sunshine server

**Expected behavior**
Apps should be sorted alphabetically, with emoji at the end

**Guest Information:**
 - Xbox Model: Xbox Series S
 - TV Resolution: 4K

**Host Information**
- Operating System: Windows 11 22H2
- Host Software: Moonlight  v0.19.1
- Monitor Resolutions: 1920x1080

**Additional context**
How the app list is sorted on the macOS client
<img width="1552" alt="Screenshot 2023-04-04 at 9 45 28 AM" src="https://user-images.githubusercontent.com/332205/229814308-c2a7885f-883c-410f-89e3-d25a7ca819e6.png">

**Comment by TheElixZammuto** [comment]
Version 1.13 now fixes this!
