### ISSUE TITLE
Request: Show app images in app list

### ISSUE THREAD

**Issue by erictbar** [TheElixZammuto/moonlight-xbox#65]
**Describe the bug**
Sunshine gives the option to show app images. On the macOS/iOS/tvOS client, these display correctly, but Moonlight UWP only shows a generic controller icon

**To Reproduce**
1. In Sunshine settings, have apps with images stored both in the Sunshine directory and on my OneDrive (with the icons in the OneDrive set to always downloaded)
2. Open Moonlight on Xbox Series S (Retail or Dev mode) and select this Sunshine server

**Expected behavior**
It would be great if these apps displayed with their box art or other images, as defined in Sunshine

**Screenshots or Videos**
If applicable, add screenshots or video recordings to help explain your problem.

** Logs **
While pressing Menu + View and then "Show Logs", are there any relevant log lines?

**Guest Information:**
 - Xbox Model: Xbox Series S
 - TV Resolution: 4K

**Host Information**
- Operating System: Windows 11 Pro 22H2
- Host Software: Sunshine v0.19.1
- Monitor Resolutions: 1920x1080

**Additional context**
How Moonlight displays on macOS
<img width="1552" alt="Screenshot 2023-04-04 at 10 57 40 AM" src="https://user-images.githubusercontent.com/332205/229833672-609c78a5-1b40-4d69-8ebd-c7674f4628bb.png">

**Comment by TheElixZammuto** [comment]
Version 1.13 now fixes this!
