### ISSUE TITLE
Black Screen Xbox One S

### ISSUE THREAD

**Issue by TriangleSteve** [TheElixZammuto/moonlight-xbox#66]
After installing Moonlight UWP and setting up my Moonlight connection, I try to enter into the connection and no matter what I try it just shows a black screen. 

I have Moonlight UWP 1.12.0.70 on the Xbox, currently hosting sunshine/moonlight on a PC with a 3060TI, no issues using Moonlight from other devices. When I enter the Moonlight connection it also appears to have no input effect to the targeted device. Is there a setting in Sunshine/Moonlight that needs to be changed for it to function correctly? This is not the digital-only Xbox One S.

**Comment by TriangleSteve** [comment]
On examining the Sunshine logs it appears to reject the connection:

[2023:04:09:14:04:16]: Info: /CN=NVIDIA GameStream Client -- verified
[2023:04:09:14:04:16]: Info: Executing [Desktop]
[2023:04:09:14:04:16]: Warning: Rejected connection from [127.0.0.1]: it's not properly set up
[2023:04:09:14:04:26]: Error: Initial Ping Timeout

**Comment by TheElixZammuto** [comment]
Can you post a screenshot of the logs on the client side? (Menu + View -> Show Logs). Also, do other clients (e.g. Android) work correctly?

**Comment by TriangleSteve** [comment]
Turns out the target device showed up automatically on the Xbox moonlight app, but it was apparently having an issue connecting through that automatic detection, so I removed the connection and added it manually and it appears to work just fine now. So this can probably be closed out, thanks for all the great work with this app!
