### ISSUE TITLE
Picture way to small for display on 720p

### ISSUE THREAD

**Issue by auyylaso** [TheElixZammuto/moonlight-xbox#67]
My TV has a strange res since it's so old. I tried connecting using the pre configured res options but the imagine doesn't stretch to fill the whole display.

**To Reproduce**
1. Have a weird res on display
2. Connect with any option. Including 1280 x 720
3. Imagine doesn't scale correctly to fit display

**Expected behavior**
Picture to fit display

**Guest Information:**
 - Xbox Model: Xbox one
 - TV Resolution: 720p 1280 x 720

**Host Information**
- Operating System: Windows
- Host Software: GeForce experience 
- 1920 x 1080

**Additional context**
Tried fiddling with the settings just ended up making the picture scale even smaller lmfao. Let me know if any of the Actions have a fix to this and I'll gladly give them a test.

**Comment by syeddaim13** [comment]
+1

Xbox One S connected to display at 1280x720 has really low picture scale.

Changing "Resolution Scale" in global settings within the app make it sliiiightly better but it's still lower than 50%.

**Host Information**

- Operating System: Windows
- Host Software: Sunshine
- 1920 x 1080

**Comment by TheElixZammuto** [comment]
Version 1.13.6 adds some changes to the swapchain that should 720p. Let me know if this works for you!

**Comment by auyylaso** [comment]
> Version 1.13.6 adds some changes to the swapchain that should 720p. Let me know if this works for you!

Works fantastic thank you so much!
