### ISSUE TITLE
Gamepad inputs breaking

### ISSUE THREAD

**Issue by Stromduster** [TheElixZammuto/moonlight-xbox#68]
Since the update 1.13.1.70 from store on Xbox series x, the ui presents the pc one, with keys from keyboard. The Xbox pad keys appears only when I'm pressing on them.
The issue might resolve itself when disconnecting/reconnecting to the stream.

Edit : on by the way, thx for the new app interface, very smooth :)

**Comment by TheElixZammuto** [comment]
Hi, can you provide me a screenshot of this issue?

**Comment by Stromduster** [comment]
Difficult to show with a picture, but I'll send a video.

https://we.tl/t-yOinFN06NM

**Comment by josealruva** [comment]
Same problem here.

**Comment by Jows23** [comment]
Here the same happens and did not happen in previous versions.

**Comment by Jows23** [comment]
I enter the game and it recognizes the xbox controller normally. After playing for about 5 minutes the bug starts, it's like the xbox controller and the keyboard and mouse get mixed up and you can't control it anymore.

**Comment by TheElixZammuto** [comment]
I have published a new version (1.13.5) that should fix this. Let me know if it does work for you!

**Comment by Jows23** [comment]
worked fine for me, thanks for the update.
