### ISSUE TITLE
Error 503 : Stage RTSP handshake failed 

### ISSUE THREAD

**Issue by tditheo** [TheElixZammuto/moonlight-xbox#71]
Hi,

When I try to connect from my Xbox One S to my HOST PC, I get this message :
`"Stage RTSP handshake failed with error 503"`

I've been tried all the settings of Moonlight (H.265, change res...) but it didn't work.

**Comment by TheElixZammuto** [comment]
Can you provide the full logs of the Moonlight app?

**Comment by tditheo** [comment]
> Can you provide the full logs of the Moonlight app?

I’ll give you these in many hours, I’m not at home now

**Comment by tditheo** [comment]
My logs are : 
`Hello from Moonlight!
Got status 0 from gs_init
Got status 0 from gs_init
Got status 0 from gs_init
Got status 0 from gs_init
Got status 0 from gs_init
Started with creation of DXView
Got status 0 from gs_init
Inserted App ID 1577243657
RTSP port: 48010
Initializing platform...Stage 1 started
Stage 1 completed
done
Resolving host name...Stage 2 started
Connection timed out after 3 seconds (TCP port 47984)
Connection timed out after 3 seconds (TCP port 47984)
Connection timed out after 3 seconds (TCP port 47984)
Connection timed out after 3 seconds (TCP port 47984)`

**Comment by tditheo** [comment]
@TheElixZammuto ?

**Comment by eduardoibarra960** [comment]
Got this message today:

...
done
Starting video stream..Stage 9 started
Using HEVC
Failed to create specified DirectX Video device: -1313558101
Video stream start failed: -1313558101
Stage 9 failed with error -1313558101
Stopping control stream .ENet peer acknowledged disconnection
done
Cleaning up input stream..done
Cleaning up video stream..done
Cleaning up control stream..done
Cleaning up audio stream..done
Cleaning up platform..done
LiStartConnection -1313558101

**Comment by tditheo** [comment]
@TheElixZammuto

**Comment by TheElixZammuto** [comment]
@tditheo please don't tag me again, I read every issue.

> Connection timed out after 3 seconds (TCP port 47984)
Check your firewall and Network configuration, there's something wrong if the client is not able to connect to the HTTP port.
Does your host work correctly with other clients on the same network? (Android, iOS, and similar?)

**Comment by TheElixZammuto** [comment]
> Got this message today (Xbox Series X):
> 
> ... done Starting video stream..Stage 9 started Using HEVC Failed to create specified DirectX Video device: -1313558101 Video stream start failed: -1313558101 Stage 9 failed with error -1313558101 Stopping control stream .ENet peer acknowledged disconnection done Cleaning up input stream..done Cleaning up video stream..done Cleaning up control stream..done Cleaning up audio stream..done Cleaning up platform..done LiStartConnection -1313558101

I think you should file another issue since the issue is completely different

**Comment by tditheo** [comment]
> @tditheo please don't tag me again, I read every issue.
> 
> > Connection timed out after 3 seconds (TCP port 47984)
> > Check your firewall and Network configuration, there's something wrong if the client is not able to connect to the HTTP port.
> > Does your host work correctly with other clients on the same network? (Android, iOS, and similar?)
> 
> Also check that you are not running GFE and Sunshine at the same time

I don't use GFE because I have an AMD gpu. Also, I can connect from my other devices without issues.

**Comment by tditheo** [comment]
Ok, I just found the source of this issue: it’s the Ethernet. When I use Moonlight with Wifi, I didn’t have any issues, but with Ethernet, I’ve always this error. So it’s a half fixed issue
