### ISSUE TITLE
Stutter on Xbox Series X

### ISSUE THREAD

**Issue by Maceeek** [TheElixZammuto/moonlight-xbox#75]
After update from 1.13.1 to the latest version, the stream is dropping frames every few seconds and causing stutter.
Previous version did not have this stutter, maybe its related to changes in SWAP_EFFECT in commit 4a199f7b946dbc5a84e5343fcaa015f764a4878b?

Happens constantly at 4K/60 FPS @120Mbit
Lowering resolution and bandwidth (1440p/60Mbit) helps a little, but the problem never really goes away.

Client:
Xbox Series X
4K TV

connected with gigabit Ethernet to
Host:
i5-12400F
Radeon RX 6800

Tested when streaming God of War. Without streaming it manages to get 90-100 FPS so it should not be performance constrain on the host (and it worked perfectly before).

Queue size shows constant 0.

**Comment by TheElixZammuto** [comment]
Are you able to provide a video sample of the problem, with the logs and stats open in the app?
