### ISSUE TITLE
RTSP Options request failed: 552 on Xbox One S

### ISSUE THREAD

**Issue by Telescuffle** [TheElixZammuto/moonlight-xbox#77]
**I see the following when trying to connect:**
`RTSP port 48010
Initializing platform...Stage I started
Stage I completed
done
Resolving host namestage 2 started
Stage 2 completed
done
Initializing audio stream„.Stage 3 started
Stage 3 completed
Starting RTSP handshake„.Stage 4 started
RTSP OPTIONS request failed: 552
failed: 552
Stage 4 failed with error 552
Cleaning up audio stream„.done
Cleaning up platform„.done
LiStartConnection 552`

**Logs show:** 
`Got status 0 from gs-init
Got status 0 from gs-init
Got status O from gs_init
Got status 0 from gs-init
Got status 0 from gs-init
Got status -5 from gs_init
Got status 0 from gs_init
Got status O from gs_init
Started with creation of DMew
Got status 0 from gs-init
Inserted App ID 550012296
RTSP port: 48010
Initializing platform...Stage 1 started
Stage 1 completed
Resolving host name...Stage 2 started
Stage 2 completed
done
Initializing audio stream..Stage 3 started
Stage 3 completed
done
Starting RTSP handshake„.Stage 4 started
RTSP OPTIONS request failed: 552
failed: 552
Stage 4 failed with error 552
Cleaning up audio stream...done
Clearing up platform...done
LiStartConnection 552`

**Comment by TheElixZammuto** [comment]
Does the same problem happen when using another client or when using Sunshine instead of GeForce Experience?

**Comment by Telescuffle** [comment]
So, other clients running moonlight work fine. However, swapping to Sunshine seems to bypass the issue. 

Let me know if there is any more info I can provide to help diagnose the issue.

**Comment by TheElixZammuto** [comment]
According to discord https://moonlight-stream.org/discord, it seems that the error 522 is specific to a broken gamestream setup. I would suggest to get help there since it does not seem to be a client-specific error
