### ISSUE TITLE
[Request] Multiple unique controllers over stream

### ISSUE THREAD

**Issue by blitz2kx** [TheElixZammuto/moonlight-xbox#80]
First off, I truly appreciate for all of the work on this. This port has come a long way and I've been daily driving it for sometime now without fail!

So I tried 2 controllers locally on my console to see if it would work over stream as 2 unique players, but unfortunately the inputs on both register as same controller.

Not sure if this is even feasible for this port but couch multiplayer via moonlight to the Xbox would be next level amazing. Just a thought! Thanks for all the work on this.

**Comment by TheElixZammuto** [comment]
Hi, I've checked with https://gamepad-tester.com/, and it works as intended. Can you check this too? Maybe it's a game issue more than a client one
