### ISSUE TITLE
Constant crashing on stream start (XSX - Retail)

### ISSUE THREAD

**Issue by m1s3ry** [TheElixZammuto/moonlight-xbox#82]
**Describe the bug**
Moonlight keeps crashing to dashboard every time I start the stream. Settings doesn't seem to matter in this case, though it fails with both h.264 and h.265, 4k resolution, etc. Higher bitrate seems to cause the crash more often (though as of the writing of this I can't even get it to work once with the default bitrate of 8000)

**To Reproduce**
1. Connect to my PC
2. Start mstsc streaming or any game

**Expected behavior**
Screen goes black for a second, then returns to dashboard

**Guest Information:**
 - Xbox Model: Xbox Series X (Retail mode)
 - TV Resolution: 4k HDR / 120hz / VRR

**Host Information**
- Operating System: Windows 10
- Host Software: Geforce Experience
- 1440p

**Comment by m1s3ry** [comment]
I am running the latest version (1.13.8). I enabled optional data sharing recently so hopefully you'll get the latest logs. However, I have a bit more insight in the problem.

It seems that disconnecting is what causes stuff to crash, in different ways, but the main problem seems to be reconnecting.
Generally, when turning on the console after shutting it down will result in the stream connecting without issue, however when disconnecting the stream and then reconnecting it seems to either crash Moonlight or directly the Xbox making it reboot.

Stuff like leaving the application by directly switching to another application using the guide button will make that when returning to Moonlight the image is frozen. Doesn't matter if you simply disconnect or disconnect with closing the app (mstsc in this case), when starting the stream again it will crash. This might happen even by disconnecting correctly before switching apps. It seems that reconnecting has a solid 90% of crashing either the app or the xbox.

**Comment by m1s3ry** [comment]
Update: It seems waiting a bit before reconnecting can improve the chances of it not crashing but it's still a solid chance of something going bananas.

**Comment by TheElixZammuto** [comment]
Version 1.14 is now live, I have tested personally and the crashes are much lower and the memory usage is much lower between connections. Let me know if this works
