### ISSUE TITLE
[Request] Add anti sleep/dim option

### ISSUE THREAD

**Issue by m1s3ry** [TheElixZammuto/moonlight-xbox#83]
I've been using this with a mouse/keyboard combo connected to my PC (weird setup, I know) and the screen dims often due to no Xbox input being registered (this also can't be disabled from Xbox, just leave it at a max of 60 minutes).

**Comment by TheElixZammuto** [comment]
Version 1.14.0 is both on Retail and Dev, the anti-dimming should be enabled
