### ISSUE TITLE
Improvment of "mouseview" alt. a "WASD+mouse" mode

### ISSUE THREAD

**Issue by zjoasan** [TheElixZammuto/moonlight-xbox#84]
**Describe the bug**
When trying to play the free PC-version of Unturned on Steam, via Sunshine (v0.20). We noticed a small inconviniance, this game doesn't support controllers on PC, as far as I can tell, but expects WASD+mouse. Whe current retail version, grabbed via "get it from MS", the mouse emulation is on the left thumb-stick, while most fps games on Xbox uses right thumbstick for "looking around".

And if I was going to bind "wasd" to any input on a xbox-controller the digipad seem most natural, haveing mouse controll on left thumbstick and "wasd" on digipad, makes it hard to play.

**To Reproduce**
1. Enable mouse mode 
2. Try to operate mouse and digipad at the same time with left thumb =)

**Expected behavior**
Since alot of older pc games are not "gamepad aware" mouse emulation is needed, but then you should be able to map a few keyboard keys to non-analog buttons. Like WASD on digipad, which removes the options to "mouse" on left thumbstick.

**Screenshots or Videos**
There is no real screenshot, but I hope I made the point clear enough

** Logs **
Nothing in logs pertaining to this issue.

**Guest Information:**
 - Xbox Model: Xbox One S,
 - TV Resolution: 1080p
 
**Host Information**
- Operating System: Windows 11 Home
- Host Software: Sunshine v.0.20.0, Steam 
- Monitor Resolutions 1080p

**Additional context**
If there is a "consensus" of most fps on Xbox (most consoles?) to use right thumbstick as "mouse view", why do anything else in a streamer client?

**Comment by TheElixZammuto** [comment]
The mouse mode is primarly made for Desktop and Menus interactions. If you want to use your gamepad to emulate a mouse/keyboard combo in games, [JoyToKey](https://joytokey.net/en/), [reWASD](https://www.rewasd.com/) or [Xpadder](https://xpadder.com/) are a much better option

**Comment by zjoasan** [comment]
Point taken, leave the conversion on the server.
