### ISSUE TITLE
Request : A way to change the back+start hotkey

### ISSUE THREAD

**Issue by Dziggify** [TheElixZammuto/moonlight-xbox#85]
It's minor, but I use a controller companion app that uses the same hotkey (back+start) to enable/disable. I know you already implement virtual mouse support which is awesome. Still, controller companion has other features like setting combo keys for lots of things (eg. binding to Alt+F4 is really convenient when you're playing an emulator to quit the app). 
So if we can customize it (I'd suggest LB+RB+RT+LT since a few of the other clients implement that), that would be great.

Thanks for the great app, I use it every day to game :)

**Comment by TheElixZammuto** [comment]
Version 1.14.0 would be soon on the store, which will allow you to set a different button combination (In this case LT+RT+LB+RB)

**Comment by TheElixZammuto** [comment]
Version 1.14.0 is both on Retail and Dev with the option to set an alternate menu popup combination!

**Comment by Dziggify** [comment]
This is awesome! Thank you @TheElixZammuto !
