### ISSUE TITLE
Queue size and latency

### ISSUE THREAD

**Issue by NouWare** [TheElixZammuto/moonlight-xbox#87]
For some reason the size of the queue increases little by little until it becomes unplayable, do you know why this might be?

I’m playing with a xbox series x wired connected to a PC with i7 10700k with a nvidia 3080 also wired.

![IMG_7589](https://github.com/TheElixZammuto/moonlight-xbox/assets/25209432/9392b977-d50a-4d52-a874-6f5dc4a65851)

**Comment by TheElixZammuto** [comment]
On which version of the app does this happen?

**Comment by NouWare** [comment]
1.14.1.70

**Comment by NouWare** [comment]
I think that maybe it is somethibg related with 60 fps. Playing Final Fantasy XV if I block the fps to 30 in the ingame cap the queue size go back to 0.

I recorded this little video to show it to you:

https://youtu.be/ga9I3P5L5T8

**Comment by j-scrizz** [comment]
I get this issue aswell.. but it's kind of random.

**Comment by hirakkopk** [comment]
I've been suffering from this lately. It seems that it had resolved in version 1.13.6, but one of the last updates brought this problem back. It happens much less compared to before version 1.13.6.

Would it be possible to add a 59 fps option in the Moonlight menu? This would be a good workaround for not having to configure each game for 59 or 55 fps

**Comment by j-scrizz** [comment]
> I've been suffering from this lately. It seems that it had resolved in version 1.13.6, but one of the last updates brought this problem back. It happens much less compared to before version 1.13.6.
> 
> Would it be possible to add a 59 fps option in the Moonlight menu? This would be a good workaround for not having to configure each game for 59 or 55 fps

Thats a great Idea. Is it possible?

**Comment by eduardoibarra960** [comment]
I also have this issue, pretty much all the time

**Comment by TheElixZammuto** [comment]
I've built version 1.14.2 with the reverted changes from 1.13.6 for the decoding subsystem. Let me know if anything improves

**Comment by j-scrizz** [comment]
> I've built version 1.14.2 with the reverted changes from 1.13.6 for the decoding subsystem. Let me know if anything improves

Didn't Fix it :(

**Comment by hirakkopk** [comment]
I've been playing these days, and it almost didn't happen. I realized that the chance of it happening increases when I disconnect and come back again while the game is open.

Playing The Sims 4 at 60 fps with Vsync on, which was impossible before version 1.13.6.
I witnessed some episodes of color anomalies in the image. I disconnected and came back, and it solved, but I suffered from the latency problem and the queue size.

How often does this happen to you? I admit that these days it almost didn't happen. Playing Full HD, 90000 Bit Rate

**Comment by floxigen** [comment]
Pretty sure the issue is happening when the GPU is rendering more than 60 fps

**Comment by floxigen** [comment]
Well I just tried with Nvidia built in frame limiter in plague tale innocence one of those game where I had the issue.

With 59 FPS frame limited I don't get any queue size increment. If I raise it to 60 I get 4-10 in few minutes.

Now I need a CLI tool for automating this if anyone has an idea

**Comment by NouWare** [comment]
> I've built version 1.14.2 with the reverted changes from 1.13.6 for the decoding subsystem. Let me know if anything improves

It is not fixed. It is 100% FPS related. I use RTS as a limiter but with the Nvidia control panel it's the same. If I lock it at 59 it stops queuing but the microstutter becomes insufferable.

Thank you very much for the work you are doing :)

**Comment by floxigen** [comment]
> > I've built version 1.14.2 with the reverted changes from 1.13.6 for the decoding subsystem. Let me know if anything improves
> 
> It is not fixed. It is 100% FPS related. I use RTS as a limiter but with the Nvidia control panel it's the same. If I lock it at 59 it stops queuing but the microstutter becomes insufferable.
> 
> Thank you very much for the work you are doing :)

 It's interesting I've don't have any stutter @59fps it works great

**Comment by floxigen** [comment]
> > > > I've built version 1.14.2 with the reverted changes from 1.13.6 for the decoding subsystem. Let me know if anything improves
> > > 
> > > 
> > > It is not fixed. It is 100% FPS related. I use RTS as a limiter but with the Nvidia control panel it's the same. If I lock it at 59 it stops queuing but the microstutter becomes insufferable.
> > > Thank you very much for the work you are doing :)
> > 
> > 
> > It's interesting I've don't have any stutter @59fps it works great
> 
> Are you blocking the FPS with RTS or Nvidia Control Panel?


Yeah rts

**Comment by TheElixZammuto** [comment]
Unfortunately I haven't managed to reproduce this on my end, but I made some blind fixes and I have uploaded version 1.14.3

It should now fix high queue size when starting a new connection, but it also should skip frames when the queue size is higher than 1 frame (similar to the iOS version)

Please check if you're actually running 1.14.3 and let me know if it works for you

**Comment by NouWare** [comment]
> Unfortunately I haven't managed to reproduce this on my end, but I made some blind fixes and I have uploaded version 1.14.3
> 
> It should now fix high queue size when starting a new connection, but it also should skip frames when the queue size is higher than 1 frame (similar to the iOS version)
> 
> Please check if you're actually running 1.14.3 and let me know if it works for you

For me it is fixed :)

Thank you very much!!

**Comment by j-scrizz** [comment]
Fixed for me.. and i dont know if an unexpected side affect... but 120fps now works too!
