### ISSUE TITLE
[Feature Request] Keyboard shortcuts

### ISSUE THREAD

**Issue by tiigerbones** [TheElixZammuto/moonlight-xbox#88]
I was wondering if it's possible to introduce keyboard shortcuts for the menu that appears with options like close and disconnect (the menu opened with View button and Menu button). 

While using Playnite + PlayNiteWatcher in full screen, having a shortcut like Alt+F4 to return to the home screen could provide a smoother experience, especially with the switchy theme.

**Comment by TheElixZammuto** [comment]
In the global settings of the app you can check the "Experimental keyboard" option, which allows you to use a Keyboard with CTRL, ALT, Shift and all of that goodies
