### ISSUE TITLE
Get status 10061 from moonlight init

### ISSUE THREAD

**Issue by Gillariel** [TheElixZammuto/moonlight-xbox#9]
Hi!
First of all, thank you for the work done, this should extend the xbox experience even more !
Using Moonlight on Android quite a lot, I wanted to check it out but I am unfortunately unable to start a game :/

Initally, I had the "Get status 10060 from moonlight init" which is supposed to be a network issue based on offical monnlight issue.

So I've disabled my Windows Firewall, allow any type of connection in Sharing Center and the error switch to : "Get status 10061 from moonlight init" which leads nowhere in Monolight repo nor Google :/

Tested with both officially supported and custom games.
Since everything works from Android, I guess the network issue should comes from the Xbox ?

Any ideas/suggestions ?
First experience in xbox dev mode so I think I should be able to provide some logs but I don't know how/where to find them sorry

Thanks for you input!

**Comment by TheElixZammuto** [comment]
Hi, seems that 10061 is a socket error given by the network layer of the Moonlight Library, on windows is the same as the error "Connection Refused". 

Are you able to open Microsoft Edge on Xbox (even on Retail) and open the page http://<ip address of GFE>:47989/serverinfo ?

If you can read the first line and the status code inside the first line is 200 then the problem lies inside Moonlight, otherwise maybe there's a network issue between the Xbox and your PC

**Comment by Gillariel** [comment]
Hi man,
Happy new year ! And thanks for your reply :)
I'm able to reach the /serverinfo EP from Xbox (retail) using my desktop IP yep, even without touching my firewall.
Just to remind, in this scenario the error I get in Moonlight on box is a 10060 which is a bit weird, I don't know why fully open my firewall would lead to a socket error while leaving it as it is brings an SSL error.
Also, pairing my device was Ok and I can get the list of apps setup on my Desktop, the problem occured when 
I try to start the stream so that you know :) 
Anyway, I have definitely not enough experience with NVidia & Moonlight to debug anything sorry :/

**Comment by SithKillerAlpha** [comment]
Don't know weather I should make a new issue or not but I am currently experiencing the same issue when and it only seems to happen when connecting to my PC from my Xbox, yet pairing had no issues.

**Comment by TheElixZammuto** [comment]
Hi, and sorry for the late response!

One other thing you can try to add these ports to your firewall configuration, maybe the http ports are online but the RTP do not.

TCP: 47984, 47989, 48010
UDP: 47998, 47999, 48000, 48002, 48010

**Comment by SilviuGamer1** [comment]
Have you tried the moonlight internet hosting tool?

**Comment by Khalidbenz7860** [comment]
has anyone managed to solve the problem?

**Comment by TheElixZammuto** [comment]
Hi, there were many changes during these months. Are you still interested to check this the newer version? Maybe some of these fixes did indirectly fix yours!
