### ISSUE TITLE
HDR Support

### ISSUE THREAD

**Issue by j-scrizz** [TheElixZammuto/moonlight-xbox#91]
Any Chance of HDR support in the future?

**Comment by TheElixZammuto** [comment]
According to microsoft, this is not possible with UWP. 

https://walbourn.github.io/directx-and-uwp-on-xbox-series-x-s/

I don't know if this can work in the future, but other software projects (like Kodi) tried and failed

**Comment by TheElixZammuto** [comment]
I Spoke with Developer and it seems applicable. I'm reopening the issue

**Comment by TheElixZammuto** [comment]
Version 1.15.2 has now HDR support. Already available for dev mode, retail would require a little bit more time

**Comment by theBeaz** [comment]
I tested in dev mode + running application as Game. Graphics are immediately distorted and artifacting (similar to the DX12 issue but immediate and outside of w/o games running).

**Comment by Uberrr** [comment]
> Version 1.15.2 has now HDR support. Already available for dev mode, retail would require a little bit more time

Any update on retail certification?

**Comment by TheElixZammuto** [comment]
> > Version 1.15.2 has now HDR support. Already available for dev mode, retail would require a little bit more time
> 
> Any update on retail certification?

Still working on that

**Comment by RecklessBoon** [comment]
Is there a way for us to petition Microsoft/Xbox to allow this HDR functionality in an app like Moonlight? I'd happily +1 an issue on their side for this if I could.

**Comment by TheElixZammuto** [comment]
I can now confirm that HDR support is available on retail now too!
