### ISSUE TITLE
Can Xbox mouse support be enabled?

### ISSUE THREAD

**Issue by healdgar** [TheElixZammuto/moonlight-xbox#94]
** feature request **
Can Xbox mouse be supported?  

**To Reproduce**
Mouse and trackpad devices do not pass through to the connected device.

**Expected behavior**
As a user, I would like to be able to connect a mouse to my xbox, or a keyboard with a mult-in trackpad and be able to use that device to move a pointer on the Windows PC to which I am connected.

**Screenshots or Videos**
N/A

** Logs **
N/A

**Guest Information:**
 - Xbox Model: [Xbox Series X]
 - TV Resolution: 4k

**Host Information**
- Operating System: Windows 11
- Host Software: Sunshine
- Monitor Resolutions: 4k, 1080p, etc.

**Additional context**
How can I help or contribute?

**Comment by TheElixZammuto** [comment]
I would love to implement this, but unfortuately UWP does not have the capability to read Mouse events yet and probably never will.

**Comment by ReenigneArcher** [comment]
It seems that RetroArch has mouse support. Is it because it's in dev mode?

https://www.reddit.com/r/XboxRetailHomebrew/s/SX8mrekKWr
