### ISSUE TITLE
Option to enable/disable V-Sync

### ISSUE THREAD

**Issue by reno911unlocred** [TheElixZammuto/moonlight-xbox#96]
The option to disable or enable v-sync to get lower latency.

Just that, the option to enable or disable v-sync. Right now there is no option and seems to be enabled by default. Compared the latency with a desktop i have just for streaming via moonlight and it seems really high. When enabling the stats it seems that at 720p or 1080p regardless the Average rendering time on an xbox one s is 13ish to 14ish ms very constant, at 50,000mbps, does not get lower either with h.265 or h.264 and regardless of bitrate.

I don't know if this is a limitation like if all xbox apps have vsync enabled by hardware like, at a driver level so it can't be done but if it can be, it would lower the imput lag significantly.

**Comment by TheElixZammuto** [comment]
This is not VSync but an hack workaround for a software/codec limitation of the Xbox One family. Unfortuntately there is some bug in the D3D11 video decoder routine which causes a very bad screen tearing. Adding a minimum wait of 12ms fixes this. You can read more here: https://github.com/TheElixZammuto/moonlight-xbox/issues/60
